const data = {
    products:[
        {
        name: 'Hanbok-white-song',
        slug:'hanbok-white-song',
        category:'Dress',
        image:'/images/white.png',
        price:120,
        stock:10,
        brand:'artist',
        rating:4.5,
        numberReviews:10,
        description:'good design, high quality',
    },
        {
            name: 'Hanbok-rice-song',
            slug:'hanbok-rice-song',
            category:'Dress',
            image:'/images/rice2.png',
            price:88,
            stock:10,
            brand:'artist',
            rating:4.5,
            numberReviews:10,
            description:'good design, high quality',
        },
        {
            name: 'Hanbok-red-song',
            slug:'hanbok-red-song',
            category:'Dress',
            image:'/images/red.png',
            price:108,
            stock:10,
            brand:'artist',
            rating:4.5,
            numberReviews:10,
            description:'good design, high quality',
        },
        {
            name: 'Hanbok-pale-green',
            slug:'hanbok-pale-green',
            category:'Dress',
            image:'images/palegreen.png',
            price:80,
            stock:10,
            brand:'artist',
            rating:4.5,
            numberReviews:10,
            description:'good design, high quality',
        },
    ],
};
export default data;